[package]
name = "my_minicom"
version = "0.1.1"
edition = "2024"

[dependencies]
ansi-to-tui = "8.0.1"
anyhow = "1.0.104"
chrono = "0.4.45"
clap = { version = "4.6.6", features = ["derive"] }
crossterm = "0.29.0"
ratatui = "0.30.2"
regex = "1.13.1"
serialport = { version = "4.9.0", default-features = false }
signal-hook = "0.4.4"

[target.'cfg(target_os = "linux")'.dependencies]
libc = "0.2.189"

[[bin]]
name = "mcom"
path = "src/main.rs"

[profile.release]
lto = true
strip = true
